Remove trailing whitespace from output (#38)
My editor automatically removed the trailing whitespace in the test
files which made the output tests fail.  It was difficult to debug
because the failing test output looked like there was no difference
between the expected output vs the actual, for example:

```
$> go test ./...
ok      github.com/leejones/kubectl-nearby      0.363s
--- FAIL: TestExecute (0.00s)
    --- FAIL: TestExecute/with_a_node_name,_returns_a_list_of_nodes_in_the_same_zone (0.00s)
        nodes_test.go:150: Expected output to contain:
            NAME      STATUS  ROLES   AGE  VERSION  ZONE
            node-a-1  Ready   <none>  60m  1.19.10  us-east4-a
            node-a-2  Ready   <none>  60m  1.19.10  us-east4-a

            got:
            NAME      STATUS  ROLES   AGE  VERSION  ZONE
            node-a-1  Ready   <none>  60m  1.19.10  us-east4-a
            node-a-2  Ready   <none>  60m  1.19.10  us-east4-a

FAIL
FAIL    github.com/leejones/kubectl-nearby/pkg/nodes    0.778s
--- FAIL: TestColumns (0.00s)
    output_test.go:59: Expected ColumnOutput to return:
        NAMESPACE   NAME               READY
        default     foo-bar-abc123     1/3
        production  baz-bat-db-def456  2/2
        --- but got: ---
        NAMESPACE   NAME               READY
        default     foo-bar-abc123     1/3
        production  baz-bat-db-def456  2/2
FAIL
FAIL    github.com/leejones/kubectl-nearby/pkg/output   0.290s
FAIL
```

I suspected it had something to do with whitespace and confirmed it by
using `git diff --ws-error-highlight=all`.

The trailing whitespace on the last column was unnecessary so I removed
it to avoid future confusion.